version: '3'
services:
  # خدمة Node.js
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://default:AafJvxunfFdxyAjZCRPodOMqseOwWxfG@gondola.proxy.rlwy.net:19042 # الربط بـ Redis
    depends_on:
      - redis # يعتمد تطبيق Node.js على Redis
    networks:
      - app-network

  # خدمة Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
