### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstName":"Sara",
  "lastName": "Ahmed",
  "age": 19,
  "email":"mohamedmrslan12@gmail.com",
  "password": "123456789"
}

### Verify code
POST http://localhost:5000/api/auth/verify-code
Content-Type: application/json

{
  "email":"mohamedmrslan12@gmail.com",
  "code": "929565"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"omer@gmail.com",
  "password": "123456789"
}