### Get all users
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NjI2NDMzLCJleHAiOjE3NDQ3MTI4MzN9.93MU1_kPVPNtH2DauGVZW6q4CQ3Oilj0zqxjo36Rszk

### Get one user
GET http://localhost:5000/api/users/26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NjI2NDMzLCJleHAiOjE3NDQ3MTI4MzN9.93MU1_kPVPNtH2DauGVZW6q4CQ3Oilj0zqxjo36Rszk

### Update user
PATCH http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NjI2NDMzLCJleHAiOjE3NDQ3MTI4MzN9.93MU1_kPVPNtH2DauGVZW6q4CQ3Oilj0zqxjo36Rszk
Content-Type: application/json

{
  "firstName":"mohamed",
  "lastName": "Shahata",
  "age": 19,
  "bio":"hello"
}

### Delete user
DELETE http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NjMzOTUzLCJleHAiOjE3NDQ3MjAzNTN9.TU6OTMVqUL4DQUOOZSkzyLBhyk4zMc_zaTds7aeLMeY

### Delete image
DELETE http://localhost:5000/api/users/images/delete-image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ0NjMzOTUzLCJleHAiOjE3NDQ3MjAzNTN9.TU6OTMVqUL4DQUOOZSkzyLBhyk4zMc_zaTds7aeLMeY
